### ISSUE TITLE
Couldnt deposit/export to Medra on OJS 3.3.0.4

### ISSUE THREAD

**Issue by rahmanramsi** [pkp/medra#1]
I just upgrade my OJS to 3.3.0-4. Unfortunately when try to deposit/exporting issue to Medra using this plugin, it doesn't work.

Specs :
PHP 7.4
xml package is installed.

Here is the stack trace :

`Fatal error: Uncaught League\Flysystem\FileNotFoundException: File not found at path: in /var/www/html/ojs3304/lib/pkp/lib/vendor/league/flysystem/src/Filesystem.php:389 Stack trace: #0 /var/www/html/ojs3304/lib/pkp/lib/vendor/league/flysystem/src/Filesystem.php(328): League\Flysystem\Filesystem->assertPresent() #1 /var/www/html/ojs3304/plugins/importexport/medra/filter/O4DOIXmlFilter.inc.php(392): League\Flysystem\Filesystem->getSize() #2 /var/www/html/ojs3304/plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php(209): O4DOIXmlFilter->createExtentNode() #3 /var/www/html/ojs3304/plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php(129): IssueMedraXmlFilter->createJournalIssueNode() #4 /var/www/html/ojs3304/plugins/importexport/medra/filter/IssueMedraXmlFilter.inc.php(73): IssueMedraXmlFilter->createIssueNode() #5 /var/www/html/ojs3304/lib/pkp/classes/filter/Filter.inc.php(449): IssueMedraXmlFilter->process() #6 /var/www/html/ojs3304/classes/plugins/PubObjectsExportPlugin.inc.php(4 in /var/www/html/ojs3304/lib/pkp/lib/vendor/league/flysystem/src/Filesystem.php on line 389`

**Comment by asmecher** [comment]
@rahmanramsi, I see you've already posted that question here: https://forum.pkp.sfu.ca/t/ojs-3-3-0-4-medra-plugin-show-fatal-error/66847

I'll close this issue and someone will follow up there. Please just post your question in one place so we can keep our resources organized.
